name       : libticalcs
version    : 1.1.9
release    : 1
source     :
    - https://downloads.sourceforge.net/project/tilp/tilp2-linux/tilp2-1.18/libticalcs2-1.1.9.tar.bz2 : 76780788bc309b647f97513d38dd5f01611c335a72855e0bd10c7bdbf2e38921
license    : GPL-2.0-or-later
component  : programming.library
summary    : TiLP calculator library
description: |
    This library is part of the TiLP project.
builddeps  :
    - pkgconfig(ticables2)
    - pkgconfig(ticonv)
    - pkgconfig(tifiles2)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
